import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CountrySearchContainer from "../components/CountrySearchContainer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Country Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CountrySearchContainer />
    </div>
  );
};

export default Home;
